Review
VictorWinberg/eitf05 pull request #42
Opened 2017-10-08 16:15 UTC by HannaLindwall

Just added a review page, some changes in navigationbar and css are required but, I wanted to meet you guys first to get approval.

2017-10-08 16:30 UTC, HannaLindwall commented
Oh yeah, added the table review in the database, so the reviews are saved there

2017-10-09 08:26 UTC, VictorWinberg requested changes
Add the review table into init.sql aswell, so a reset of our database works

2017-10-09 09:12 UTC, HannaLindwall commented
Added!

2017-10-11 11:20 UTC, VictorWinberg approved these changes

2017-10-11 11:20 UTC, merged